### ISSUE TITLE
[Feature request] Add `config` subcommand

### ISSUE THREAD

**Issue by JamyGolden** [tinted-theming/tinty#21]
## Is your feature request related to a problem? Please describe.

It can be difficult to debug some issues since it isn't clear what config is being used. There have been times, like here: https://github.com/tinted-theming/tinty/issues/19, where someone was editing a config but that config wasn't being used by tinty.

## Describe the solution you'd like

Add a subcommand to return the config file and/or the path to config/data dirs.

**Comment by laenzlinger** [comment]
`chezmoi` has a `cat-config` sub command which might also be an option https://www.chezmoi.io/reference/commands/cat-config/

Unrelated (similar) is the `cd` command, which could be useful to switch into the data directory: https://www.chezmoi.io/reference/commands/cd/
