### ISSUE TITLE
[Feature request] Allow silent completion generation

### ISSUE THREAD

**Issue by conways-glider** [tinted-theming/tinty#26]
## Is your feature request related to a problem? Please describe.

This is super nitpicky, but I'd love to be able to handle completion without the `Generating completion file for bash...` text.

## Describe the solution you'd like

I would like an additional CLI flag, perhaps something like `--silent`.

## Describe alternatives you've considered

- Updating default behavior to remove the line, but to allow it to be generated with a flag. (This seems like an anti-pattern to me)
- Removing the line altogether

## Additional context

N/A

**Comment by JamyGolden** [comment]
Thanks for the github issue. I've decided to just remove it since it doesn't actually serve any purpose. If someone runs `tinty generate-completion zsh` they know the following code is a zsh completion. I also added some more docs about it: https://github.com/tinted-theming/tinty/pull/27
