### ISSUE TITLE
Hook execution in current shell

### ISSUE THREAD

**Issue by pardom** [tinted-theming/tinty#28]
I'm trying to take advantage of the `BASE16_SHELL_ENABLE_VARS` exports in [tinted-theming/tinted-shell](https://github.com/tinted-theming/tinted-shell). I can set the `BASE16_COLOR_##_HEX` exports correctly if I source the script from my current shell like so: 

```source "$(tinty config --data-dir-path)/base16-shell-scripts-file.sh"```

However, when I apply a scheme via `tinty apply` these exports are not set. I assume this is because hooks are executed via shell command instead of executing in the current shell. Is there a workaround for this that will allow the hook to run in the current shell?

**What version of `tinty` are you using?**
`0.14.0`

**Comment by JamyGolden** [comment]
Hello! Yes there is a workaround: https://github.com/tinted-theming/tinty/blob/main/USAGE.md#sourcing-scripts-that-set-environment-variables

**Comment by pardom** [comment]
Thanks!
