### ISSUE TITLE
[Question]  alacritty

### ISSUE THREAD

**Issue by windowsrefund** [tinted-theming/tinty#54]
**What version of `tinty` are you using?**
0.18.0

Thank you for your work on this project. After noticing your [tinted-alacritty](https://github.com/tinted-theming/tinted-alacritty) repo, I've gone ahead and setup a minimal `~/.config/tinted-theming/tinty/config.toml`

```
[[items]]
path = "https://github.com/tinted-theming/tinted-alacritty"
name = "base16-alacritty"
themes-dir = "colors"
hook = "cp -f %f ~/.config/alacritty/colors.toml"
```
This config is confirmed via the output from `tinty config`

```
shell = "sh -c '{}'"

[[items]]
name = "base16-alacritty"
path = "https://github.com/tinted-theming/tinted-alacritty"
hook = "cp -f %f ~/.config/alacritty/colors.toml"
supported-systems = ["base16"]
themes-dir = "colors"

```

That said, I don't see a `~/.config/alacritty/colors.toml` file being written after I `tinty apply` a theme.

Should we be using that repo? The current migration [documentation](https://github.com/tinted-theming/tinty#migration-from-flavours) still mentions the repo you forked.

**Comment by windowsrefund** [comment]
OK, figured it out. It seems a `tinty install` is needed every time a new a repo is added to the config.

**Comment by JamyGolden** [comment]
Glad you sorted it out. I'm going to add a new command `tinty sync` which will `tinty install && tinty update` to make it more simple to reason about.
