### ISSUE TITLE
[Question] AUR packaging

### ISSUE THREAD

**Issue by loiccoyle** [tinted-theming/tinty#76]
With your permission, I would like to package `tinty` on the [Arch User Repository](https://aur.archlinux.org/) so that it can easily be installed and updated for arch linux users. I would package it as `tinty-git` so that it follows the HEAD of this repo. Let me know what you think.

**Comment by JamyGolden** [comment]
Hey, yeah it would be great if you could do that. Could you create a PR with updates to the readme to include the installation instructions for arch when the package is listed?

**Comment by loiccoyle** [comment]
Great! Will do.
